[package]
name = "leaftext"
version = "0.1.325"
edition = "2021"

[profile.release]
strip = true
lto = "thin"
codegen-units = 1

[dependencies]
ammonia = "4.1.2"
arboard = "3.4"
blake3 = "1"
directories = "6.0.0"
html-escape = "0.2.13"
linkify = "0.11.0"
notify-debouncer-mini = "0.4"
png = "0.17.16"
pulldown-cmark = "0.13.4"
rfd = "0.17.2"
roxmltree = "0.20"
rusqlite = { version = "0.31", features = ["bundled"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
syntect = "5.3.0"
tao = "0.35.3"
trash = "5.2"
two-face = "0.5.1"
url = "2.5.8"
wry = "0.55.1"

[target.'cfg(windows)'.build-dependencies]
embed-resource = "2.5"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = [
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_System_Pipes",
    "Win32_System_IO",
    "Win32_Storage_FileSystem",
    "Win32_Security",
] }
